export { SignInPage, SignUpPage } from "./auth"
export { ExerciseDetailsPage } from "./exercise"
export { ExercisesPage } from "./exercises"
export { HomePage } from "./home"
export { NotFoundPage } from "./not-found"
export { WorkoutsHistoryPage } from "./workouts-history"
